DELETE COMPUTADOR;

INSERT INTO COMPUTADOR(marca, modelo) VALUES ("ASUS", "CORE I7");
INSERT INTO COMPUTADOR(marca, modelo) VALUES ("HP", "CORE9");
INSERT INTO COMPUTADOR(marca, modelo) VALUES ("COMPAQ", "CORE5");